### ISSUE TITLE
License is missing - WTFPL good choice?

### ISSUE THREAD

**Issue by kocio-pl** [kosmtik/kosmtik#169]
In fact the only place I could find the license is [inside package.json file](https://github.com/kosmtik/kosmtik/blob/master/package.json#L19). Proper LICENSE(.md) file would be good to have.

**Comment by nebulon42** [comment]
I think this is a good opportunity to partly hijack this and ask if it is a good idea to have WTFPL as license? While the intend is good I think WTFPL isn't that good. It does not disclaim warranties and uses language that may be offensive to some.

Better alternatives?
* https://github.com/adversary-org/wtfnmf (still language that may sound offensive)
* Same as WTFPL with disclaimer and without F*: http://unlicense.org/
* MIT License: https://opensource.org/licenses/MIT

Does every contributor have to be asked about that? Maybe that's not feasible then.

**Comment by nebulon42** [comment]
@yohanboniface Asking you directly: Would you be in favour of a license change? I would then try to coordinate the process with the contributors. I recommend either Unlicense.org or MIT license.

**Comment by yohanboniface** [comment]
I'm OK, and both unlicence and MIT are good choices. We could also align to [Mapnik](https://github.com/mapnik/mapnik#license) choice, given that this project is mainly an UI for Mapnik.

I'm not going to make the final choice here yet, given that my choice was WTFPL, so let's see how the interested people here around want to push this out :)

**Comment by pnorman** [comment]
I think the issue of the missing license file and changing the license should be split. The fix to the first is trivial, the second requires discussion.

> I'm OK, and both unlicence and MIT are good choices. We could also align to Mapnik choice, given that this project is mainly an UI for Mapnik.

LGPL makes sense for Mapnik because it's a library. Kosmtik is a stand-alone program, so although there's nothing wrong with LGPL, it's not an obvious choice for here.

I'm fine with WTFPL.

**Comment by nebulon42** [comment]
I have created #181 to fix the first part.

**Comment by nebulon42** [comment]
My main concern was the missing disclaimer, but there was a version of WTFPL which included it (https://github.com/kosmtik/kosmtik/blob/master/LICENSE#L3). So I will not pursue a license change further and since the original issue post was about the missing LICENSE file and this is now fixed I will close this.
