### ISSUE TITLE
Compatible node.js versions not mentioned

### ISSUE THREAD

**Issue by jojo4u** [kosmtik/kosmtik#185]
I'm totally new to the node.js/npm stuff and lost some time trying to get Kosmtik to run with the default node.js of my Arch Linux. Node.js 7 and 6 did not work, 5 finally did. I would like to have "tested with" node.js versions ... on the README.md. Currently it is only documented in #143 and on <s>.travis.yml</s> https://travis-ci.org/kosmtik/kosmtik.

**Comment by nebulon42** [comment]
We are really dependent here on node-mapnik. If this fails we run into trouble, but cannot do a great deal about it. But I agree that this should get tested and mentioned.

**Comment by yohanboniface** [comment]
As said by @nebulon42 we are mainly dependent on node-mapnik, and NodeJS versions are moving so fast that it would need to update the README very often.
What I usually try to do is to make sure it work on the last LTS, when it changes.

> trying to get Kosmtik to run with the default node.js of my Arch Linux

I'm also on Arch. Best thing with NodeJS is to run away, but if you can't and you really need to use it, you need a version manager, like NVM (I'm using Fish and the FNM plugin myself), because there is a new version out every three days and all the ecosystem is like "release and run". So with a version manager you can stay on a more or less stable path.
